use super::*;

macro_rules! typed_domain_tool {
    ($router:expr, $name:literal, $request:ty, $result:ty, $method:ident, $mutation:literal, $convert:ident) => {
        $router.add_route(ToolRoute::new_dyn(
            Tool::new(
                $name,
                operation_description($name),
                rmcp::handler::server::tool::schema_for_type::<$request>(),
            )
            .with_raw_output_schema(rmcp::handler::server::tool::schema_for_type::<$result>()),
            |context: ToolCallContext<'_, CollaborationMcpServer>| {
                Box::pin(async move {
                    let request = match serde_json::from_value::<$request>(
                        serde_json::Value::Object(context.arguments.unwrap_or_default()),
                    ) {
                        Ok(value) => value,
                        Err(error) => {
                            return Ok(CallToolResponse::Complete(validation_failure(
                                &error.to_string(),
                            )));
                        }
                    };
                    let mut client = match context.service.connect().await {
                        Ok(value) => value,
                        Err(error) => {
                            return Ok(CallToolResponse::Complete(failure(
                                error,
                                OperationEffect::None,
                            )));
                        }
                    };
                    let result = client.$method(request).await;
                    let _closed = client.close().await;
                    Ok(CallToolResponse::Complete($convert(result, $mutation)))
                })
            },
        ));
    };
}

pub(super) fn register_automation_mutation_tools(router: &mut ToolRouter<CollaborationMcpServer>) {
    use collaboration_protocol::*;
    typed_domain_tool!(
        router,
        "instruction_create",
        InstructionCreateParams,
        InstructionSnapshot,
        create_instruction,
        true,
        instruction_result
    );
    typed_domain_tool!(
        router,
        "instruction_update",
        InstructionUpdateParams,
        InstructionSnapshot,
        update_instruction,
        true,
        instruction_result
    );
    typed_domain_tool!(
        router,
        "instruction_show",
        InstructionShowParams,
        InstructionSnapshot,
        read_instruction,
        false,
        instruction_result
    );
    typed_domain_tool!(
        router,
        "wake_send",
        WakeSendRequest,
        WakeSnapshot,
        send_wakeup,
        true,
        wake_result
    );
    typed_domain_tool!(
        router,
        "wake_show",
        WakeShowRequest,
        WakeSnapshot,
        read_wakeup,
        false,
        wake_result
    );
    typed_domain_tool!(
        router,
        "wake_pause",
        WakeMutationRequest,
        WakeMutationResult,
        pause_wakeup,
        true,
        wake_result
    );
    typed_domain_tool!(
        router,
        "wake_resume",
        WakeMutationRequest,
        WakeMutationResult,
        resume_wakeup,
        true,
        wake_result
    );
    typed_domain_tool!(
        router,
        "wake_cancel",
        WakeMutationRequest,
        WakeMutationResult,
        cancel_wakeup,
        true,
        wake_result
    );
    typed_domain_tool!(
        router,
        "delivery_show",
        DeliveryShowRequest,
        DeliveryInspection,
        read_delivery,
        false,
        wake_result
    );
    typed_domain_tool!(
        router,
        "wake_list",
        AutomationPageRequest,
        AutomationPage<WakeSnapshot>,
        list_wakeups,
        false,
        wake_result
    );
    typed_domain_tool!(
        router,
        "schedule_import",
        ScheduleImportRequest,
        ScheduleSnapshot,
        import_schedule,
        true,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "schedule_export",
        ScheduleShowRequest,
        ScheduleExportResult,
        export_schedule,
        false,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "schedule_create",
        ScheduleCreateRequest,
        ScheduleSnapshot,
        create_schedule,
        true,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "schedule_update",
        ScheduleUpdateRequest,
        ScheduleSnapshot,
        update_schedule,
        true,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "schedule_show",
        ScheduleShowRequest,
        ScheduleSnapshot,
        read_schedule,
        false,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "schedule_enable",
        ScheduleEnableRequest,
        ScheduleSnapshot,
        enable_schedule,
        true,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "schedule_disable",
        ScheduleEnableRequest,
        ScheduleSnapshot,
        disable_schedule,
        true,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "schedule_prepare",
        SchedulePrepareRequest,
        ScheduleSnapshot,
        prepare_schedule,
        true,
        schedule_result
    );
    typed_domain_tool!(
        router,
        "run_show",
        RunShowRequest,
        RunSnapshot,
        read_run,
        false,
        run_result
    );
    typed_domain_tool!(
        router,
        "run_summary_retry",
        RunRecoveryRequest,
        RunSnapshot,
        retry_summary,
        true,
        run_result
    );
    typed_domain_tool!(
        router,
        "run_summary_skip",
        RunRecoveryRequest,
        RunSnapshot,
        skip_summary,
        true,
        run_result
    );
    typed_domain_tool!(
        router,
        "automation_configure",
        AutomationConfigureRequest,
        AutomationConfiguration,
        configure_automation,
        true,
        configuration_result
    );
}

macro_rules! automation_inspection_tool {
    ($router:expr, $name:literal, $request:ty, $result:ty, $method:ident) => {
        $router.add_route(ToolRoute::new_dyn(
            Tool::new(
                $name,
                operation_description($name),
                rmcp::handler::server::tool::schema_for_type::<$request>(),
            )
            .with_raw_output_schema(rmcp::handler::server::tool::schema_for_type::<$result>()),
            |context: ToolCallContext<'_, CollaborationMcpServer>| {
                Box::pin(async move {
                    let request = match serde_json::from_value::<$request>(
                        serde_json::Value::Object(context.arguments.unwrap_or_default()),
                    ) {
                        Ok(value) => value,
                        Err(error) => {
                            return Ok(CallToolResponse::Complete(validation_failure(
                                &error.to_string(),
                            )));
                        }
                    };
                    let mut client = match context.service.connect().await {
                        Ok(value) => value,
                        Err(error) => {
                            return Ok(CallToolResponse::Complete(failure(
                                error,
                                OperationEffect::None,
                            )));
                        }
                    };
                    let result = client.$method(request).await;
                    let _closed = client.close().await;
                    Ok(CallToolResponse::Complete(automation_inspection_result(
                        result,
                    )))
                })
            },
        ));
    };
}

pub(super) fn register_automation_inspection_tools(
    router: &mut ToolRouter<CollaborationMcpServer>,
) {
    use collaboration_protocol::*;
    automation_inspection_tool!(
        router,
        "run_reconcile",
        RunShowRequest,
        RunSnapshot,
        reconcile_run
    );
    automation_inspection_tool!(
        router,
        "delivery_reconcile",
        DeliveryShowRequest,
        DeliveryInspection,
        reconcile_delivery
    );
    automation_inspection_tool!(
        router,
        "operation_show",
        OperationShowRequest,
        OperationSnapshot,
        read_operation
    );
    automation_inspection_tool!(
        router,
        "operation_reconcile",
        OperationShowRequest,
        OperationSnapshot,
        reconcile_operation
    );
    automation_inspection_tool!(
        router,
        "automation_events",
        AutomationEventsRequest,
        AutomationEventsPage,
        read_automation_events
    );
    automation_inspection_tool!(
        router,
        "delivery_attempts",
        DeliveryAttemptsRequest,
        AttemptHistoryPage<AttemptInspection>,
        read_delivery_attempts
    );
    automation_inspection_tool!(
        router,
        "run_summaries",
        RunSummariesRequest,
        AttemptHistoryPage<SummaryInspection>,
        read_run_summaries
    );
    automation_inspection_tool!(
        router,
        "instruction_list",
        AutomationPageRequest,
        AutomationPage<InstructionSnapshot>,
        list_instructions
    );
    automation_inspection_tool!(
        router,
        "schedule_list",
        AutomationPageRequest,
        AutomationPage<ScheduleSnapshot>,
        list_schedules
    );
    automation_inspection_tool!(
        router,
        "run_list",
        RunListRequest,
        AutomationPage<RunSnapshot>,
        list_runs
    );
    automation_inspection_tool!(
        router,
        "delivery_list",
        DeliveryListRequest,
        AutomationPage<DeliveryInspection>,
        list_deliveries
    );
    automation_inspection_tool!(
        router,
        "revision_list",
        RevisionListRequest,
        AutomationPage<RevisionRecord>,
        list_instruction_revisions
    );
}

macro_rules! board_tool {
    ($router:expr, $name:literal, $request:ty, $result:ty, $method:ident, $mutation:literal) => {
        $router.add_route(ToolRoute::new_dyn(
            Tool::new(
                $name,
                operation_description($name),
                rmcp::handler::server::tool::schema_for_type::<$request>(),
            )
            .with_raw_output_schema(rmcp::handler::server::tool::schema_for_type::<$result>()),
            |context: ToolCallContext<'_, CollaborationMcpServer>| {
                Box::pin(async move {
                    let request = match serde_json::from_value::<$request>(
                        serde_json::Value::Object(context.arguments.unwrap_or_default()),
                    ) {
                        Ok(value) => value,
                        Err(error) => {
                            return Ok(CallToolResponse::Complete(validation_failure(
                                &error.to_string(),
                            )));
                        }
                    };
                    let mut client = match context.service.connect().await {
                        Ok(value) => value,
                        Err(error) => {
                            return Ok(CallToolResponse::Complete(failure(
                                error,
                                OperationEffect::None,
                            )));
                        }
                    };
                    let result = client.$method(request).await;
                    let _closed = client.close().await;
                    Ok(CallToolResponse::Complete(board_result(result, $mutation)))
                })
            },
        ));
    };
}

pub(super) fn register_board_tools(router: &mut ToolRouter<CollaborationMcpServer>) {
    use collaboration_client::board::*;
    board_tool!(
        router,
        "board_discovery_search",
        DiscoverySearchRequest,
        DiscoverySearchResult,
        board_discovery_search,
        false
    );
    board_tool!(
        router,
        "board_message_search",
        MessageSearchRequest,
        MessageSearchResult,
        board_message_search,
        false
    );
    board_tool!(
        router,
        "board_project_create",
        ProjectCreateRequest,
        ProjectCreateResult,
        board_project_create,
        true
    );
    board_tool!(
        router,
        "board_project_update",
        ProjectUpdateRequest,
        ProjectUpdateResult,
        board_project_update,
        true
    );
    board_tool!(
        router,
        "board_project_show",
        ProjectShowRequest,
        ProjectShowResult,
        board_project_show,
        false
    );
    board_tool!(
        router,
        "board_project_list",
        ProjectListRequest,
        ProjectListResult,
        board_project_list,
        false
    );
    board_tool!(
        router,
        "board_repository_attach",
        RepositoryAttachRequest,
        RepositoryAttachResult,
        board_repository_attach,
        true
    );
    board_tool!(
        router,
        "board_repository_detach",
        RepositoryDetachRequest,
        RepositoryDetachResult,
        board_repository_detach,
        true
    );
    board_tool!(
        router,
        "board_repository_list",
        RepositoryListRequest,
        RepositoryListResult,
        board_repository_list,
        false
    );
    board_tool!(
        router,
        "board_create",
        BoardCreateRequest,
        BoardCreateResult,
        board_create,
        true
    );
    board_tool!(
        router,
        "board_update",
        BoardUpdateRequest,
        BoardUpdateResult,
        board_update,
        true
    );
    board_tool!(
        router,
        "board_show",
        BoardShowRequest,
        BoardShowResult,
        board_show,
        false
    );
    board_tool!(
        router,
        "board_list",
        BoardListRequest,
        BoardListResult,
        board_list,
        false
    );
    board_tool!(
        router,
        "board_archive",
        BoardArchiveRequest,
        BoardArchiveResult,
        board_archive,
        true
    );
    board_tool!(
        router,
        "board_topic_create",
        TopicCreateRequest,
        TopicCreateResult,
        board_topic_create,
        true
    );
    board_tool!(
        router,
        "board_topic_update",
        TopicUpdateRequest,
        TopicUpdateResult,
        board_topic_update,
        true
    );
    board_tool!(
        router,
        "board_topic_list",
        TopicListRequest,
        TopicListResult,
        board_topic_list,
        false
    );
    board_tool!(
        router,
        "board_message_post",
        MessagePostRequest,
        MessagePostResult,
        board_message_post,
        true
    );
    board_tool!(
        router,
        "board_message_show",
        MessageShowRequest,
        MessageShowResult,
        board_message_show,
        false
    );
    board_tool!(
        router,
        "board_message_list",
        MessageListRequest,
        MessageListResult,
        board_message_list,
        false
    );
    board_tool!(
        router,
        "board_thread_show",
        ThreadShowRequest,
        ThreadShowResult,
        board_thread_show,
        false
    );
    board_tool!(
        router,
        "board_thread_resolve",
        ThreadResolveRequest,
        ThreadResolveResult,
        board_thread_resolve,
        true
    );
    board_tool!(
        router,
        "board_thread_unresolve",
        ThreadUnresolveRequest,
        ThreadUnresolveResult,
        board_thread_unresolve,
        true
    );
    board_tool!(
        router,
        "board_thread_watch",
        ThreadWatchRequest,
        ThreadWatchResult,
        board_thread_watch,
        true
    );
    board_tool!(
        router,
        "board_thread_unwatch",
        ThreadUnwatchRequest,
        ThreadUnwatchResult,
        board_thread_unwatch,
        true
    );
    board_tool!(
        router,
        "board_topic_watch",
        TopicWatchRequest,
        TopicWatchResult,
        board_topic_watch,
        true
    );
    board_tool!(
        router,
        "board_topic_unwatch",
        TopicWatchRequest,
        TopicWatchResult,
        board_topic_unwatch,
        true
    );
    board_tool!(
        router,
        "board_thread_list",
        ThreadListRequest,
        ThreadListResult,
        board_thread_list,
        false
    );
    board_tool!(
        router,
        "board_thread_create",
        ThreadCreateRequest,
        ThreadCreateResult,
        board_thread_create,
        true
    );
    board_tool!(
        router,
        "board_thread_join",
        ThreadJoinRequest,
        ThreadJoinResult,
        board_thread_join,
        true
    );
    board_tool!(
        router,
        "board_thread_leave",
        ThreadLeaveRequest,
        ThreadLeaveResult,
        board_thread_leave,
        true
    );
    board_tool!(
        router,
        "board_thread_participant_list",
        ThreadParticipantListRequest,
        ThreadParticipantListResult,
        board_thread_participant_list,
        false
    );
    board_tool!(
        router,
        "board_thread_listen",
        ThreadListenRequest,
        ThreadListenResult,
        board_thread_listen,
        false
    );
    board_tool!(
        router,
        "board_thread_listen_show",
        ThreadListenShowRequest,
        ThreadListenShowResult,
        board_thread_listen_show,
        false
    );
    board_tool!(
        router,
        "board_thread_listen_cancel",
        ThreadListenCancelRequest,
        ThreadListenCancelResult,
        board_thread_listen_cancel,
        true
    );
    board_tool!(
        router,
        "board_inbox_fetch",
        InboxFetchRequest,
        InboxFetchResult,
        board_inbox_fetch,
        true
    );
    board_tool!(
        router,
        "board_inbox_acknowledge",
        InboxAcknowledgeRequest,
        InboxAcknowledgeResult,
        board_inbox_acknowledge,
        true
    );
    board_tool!(
        router,
        "board_inbox_projects",
        InboxProjectsRequest,
        InboxProjectsResult,
        board_inbox_projects,
        false
    );
}

#[derive(Debug, Default, Deserialize, schemars::JsonSchema)]
#[serde(deny_unknown_fields)]
pub(super) struct EmptyToolInput {}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(super) struct ThreadWaitToolInput {
    pub(super) request: collaboration_client::board::ThreadWaitRequest,
    #[schemars(range(min = 1, max = 1500))]
    pub(super) timeout_seconds: u64,
}
