//! Foreground lifecycle control for one shared Codex app-server.

mod app_server_endpoint_guard;
mod app_server_shutdown;
mod changed_update_activation;
mod codex_update_preparation;
mod explicit_app_server_restart;
mod explicit_router_restart;
mod host_configuration;
mod host_singleton_authority;
mod lifecycle_owner;
mod lifecycle_state;
mod lifecycle_telemetry;
mod managed_app_server;
mod operator_connection;
mod operator_messages;
mod owned_router;
mod process_group_child;
mod router_compatibility;

pub use app_server_endpoint_guard::AppServerEndpointError;
pub use app_server_endpoint_guard::require_unowned_app_server_endpoint;
pub use app_server_shutdown::APP_SERVER_FORCE_AFTER;
pub use app_server_shutdown::APP_SERVER_SHUTDOWN_TOTAL;
pub use app_server_shutdown::AppServerShutdownDeadlines;
pub use app_server_shutdown::AppServerShutdownError;
pub use app_server_shutdown::ExpectedExit;
pub use app_server_shutdown::ShutdownAction;
pub use app_server_shutdown::ShutdownOutcome;
pub use managed_app_server::AppServerChild;
pub use managed_app_server::AppServerLaunchPlan;
pub use managed_app_server::AppServerReadiness;
pub use managed_app_server::AppServerReadinessError;

pub use codex_update_preparation::UpdateDeadlineError;
pub use codex_update_preparation::UpdateDeadlines;
pub use codex_update_preparation::UpdateResult;
pub use host_configuration::HostConfig;
pub use host_configuration::HostConfigInputs;
pub use host_configuration::HostCoordinationPaths;
pub use host_configuration::HostDeadlineError;
pub use host_configuration::HostDeadlineInputs;
pub use host_configuration::HostDeadlines;
pub use host_singleton_authority::HostInstance;
pub use host_singleton_authority::InstanceAcquireError;
pub use host_singleton_authority::inherited_lock_environment;
pub use host_singleton_authority::inherited_lock_marker;
pub use lifecycle_owner::HostDependencies;
pub use lifecycle_owner::HostDependenciesInputs;
pub use lifecycle_owner::HostError;
pub use lifecycle_owner::HostExit;
pub use lifecycle_owner::HostRuntime;
pub use lifecycle_owner::PreExecTelemetry;
pub use lifecycle_state::AppServerCondition;
pub use lifecycle_state::ExecutableRelation;
pub use lifecycle_state::HostOperation;
pub use lifecycle_state::HostPhase;
pub use lifecycle_state::HostSnapshot;
pub use lifecycle_state::HostSnapshotDimensions;
pub use lifecycle_state::HostedReadiness;
pub use lifecycle_state::LifecycleOutcome;
pub use lifecycle_state::LifecycleOutcomeClassification;
pub use lifecycle_state::RecoveryBudget;
pub use lifecycle_state::RemoteControlCondition;
pub use lifecycle_state::RouterCondition;
pub use operator_messages::HostProgress;
pub use operator_messages::HostTerminalResponse;
pub use operator_messages::MAX_OPERATOR_FRAME_BYTES;
pub use operator_messages::MutationAdmission;
pub use operator_messages::OPERATOR_PROTOCOL_VERSION;
pub use operator_messages::OperatorFrame;
pub use operator_messages::OperatorProtocolError;
pub use operator_messages::OperatorRequest;
pub use operator_messages::TerminalClassification;
pub use operator_messages::classify_operator_request;
pub use operator_messages::decode_operator_frame;
pub use operator_messages::decode_operator_request;
pub use operator_messages::encode_operator_frame;
pub use operator_messages::encode_operator_request;
pub use owned_router::ROUTER_SHUTDOWN_TIMEOUT;
pub use owned_router::RouterChild;
pub use owned_router::RouterOwnership;
pub use owned_router::RouterShutdownError;
pub use owned_router::RouterShutdownOutcome;
pub use process_group_child::ChildCommandSpec;
pub use process_group_child::ChildOutput;
pub use process_group_child::ProcessGroupChild;
pub use process_group_child::ProcessGroupError;
pub use router_compatibility::RouterProbeError;
pub use router_compatibility::RouterProbeResult;
pub use router_compatibility::probe_router;
