//! Foreground lifecycle control for one shared Codex app-server.

mod app_server;
mod config;
mod domain;
mod instance;
mod operator_protocol;
mod process;
mod router;
mod runtime;
mod telemetry;

pub use app_server::APP_SERVER_FORCE_AFTER;
pub use app_server::APP_SERVER_SHUTDOWN_TOTAL;
pub use app_server::AppServerChild;
pub use app_server::AppServerEndpointError;
pub use app_server::AppServerLaunchPlan;
pub use app_server::AppServerReadiness;
pub use app_server::AppServerReadinessError;
pub use app_server::AppServerShutdownDeadlines;
pub use app_server::AppServerShutdownError;
pub use app_server::ExpectedExit;
pub use app_server::ShutdownAction;
pub use app_server::ShutdownOutcome;
pub use app_server::require_unowned_app_server_endpoint;

pub use config::HostConfig;
pub use config::HostConfigInputs;
pub use config::HostCoordinationPaths;
pub use config::HostDeadlineError;
pub use config::HostDeadlineInputs;
pub use config::HostDeadlines;
pub use domain::AppServerCondition;
pub use domain::ExecutableRelation;
pub use domain::HostOperation;
pub use domain::HostPhase;
pub use domain::HostSnapshot;
pub use domain::HostSnapshotDimensions;
pub use domain::HostedReadiness;
pub use domain::LifecycleOutcome;
pub use domain::LifecycleOutcomeClassification;
pub use domain::RecoveryBudget;
pub use domain::RemoteControlCondition;
pub use domain::RouterCondition;
pub use instance::HostInstance;
pub use instance::InstanceAcquireError;
pub use instance::inherited_lock_marker;
pub use operator_protocol::HostTerminalResponse;
pub use operator_protocol::MutationAdmission;
pub use operator_protocol::OPERATOR_PROTOCOL_VERSION;
pub use operator_protocol::OperatorClientError;
pub use operator_protocol::OperatorFrame;
pub use operator_protocol::OperatorProtocolError;
pub use operator_protocol::OperatorRequest;
pub use operator_protocol::TerminalClassification;
pub use operator_protocol::classify_operator_request;
pub use operator_protocol::decode_operator_frame;
pub use operator_protocol::decode_operator_request;
pub use operator_protocol::encode_operator_frame;
pub use operator_protocol::encode_operator_request;
pub use operator_protocol::send_operator_request;
pub use process::ChildCommandSpec;
pub use process::ChildOutput;
pub use process::ProcessGroupChild;
pub use process::ProcessGroupError;
pub use router::ROUTER_SHUTDOWN_TIMEOUT;
pub use router::RouterChild;
pub use router::RouterOwnership;
pub use router::RouterProbeError;
pub use router::RouterProbeResult;
pub use router::RouterShutdownError;
pub use router::RouterShutdownOutcome;
pub use router::probe_router;
pub use runtime::HostDependencies;
pub use runtime::HostDependenciesInputs;
pub use runtime::HostError;
pub use runtime::HostExit;
pub use runtime::HostRuntime;
