[package]
name = "project-board-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
[lints]
workspace = true
[dependencies]
base64.workspace = true
hmac.workspace = true
sha2.workspace = true
project-board = { path = "../project-board", version = "0.1.20" }
sqlx = { workspace = true, features = ["macros", "migrate"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
[dev-dependencies]
tokio.workspace = true
